### ISSUE TITLE
Non-JS way of tweaking `overlaysContent`

### ISSUE THREAD

**Issue by bramus** [w3c/virtual-keyboard#13]
Whilst the goal of this API is great, I find it a shortcoming that JS is required to change the value of `overlaysContent`. Don't know if this is for security reasons or something else, but an extension to `meta name="viewport"` _(or perhaps a new CSS at-rule or property on `<html>`)_ to control the behavior seems like something handier.

Something like this:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, virtual-keyboard=overlays-content">
```

Or this:

```css
html {
  virtual-keyboard: overlays-content;
}
```

_(names to be bikeshed but you get the point)_

**Comment by snianu** [comment]
Agreed. A declarative mechanism should be provided by the VK API to set the `overlaysContent` flag. There is an [existing issue](https://github.com/w3c/virtual-keyboard/issues/3) already :). I've opened a [crbug ](https://bugs.chromium.org/p/chromium/issues/detail?id=1250883)to track this issue in Chromium.

**Comment by bramus** [comment]
Duplicate of #3. Closing.
