### ISSUE TITLE
Question: API isn't accessible in unsecure context?

### ISSUE THREAD

**Issue by woody-li** [w3c/virtual-keyboard#20]
Only allows show(), hide(), overlayscontent in secure context.

What about other information, such as boundingrect?

Chrome navigator.virtualKeyboard is undefined in un-secure context for now, is it correct?

**Comment by HolgerJeromin** [comment]
> Chrome navigator.virtualKeyboard is undefined in un-secure context for now, is it correct?

according to the spec yes:
https://www.w3.org/TR/virtual-keyboard/#idl-index


```idl
partial interface Navigator {
    [SecureContext, SameObject] readonly attribute VirtualKeyboard virtualKeyboard;
};

**Comment by woody-li** [comment]
@HolgerJeromin Thanks for your reply.

Is it possibile to provide any API/method to get the visible status of virtualKeyboard in any context.

I think the only getter should not privacy/secure associated probably.
