### ISSUE TITLE
Future Usage of VirtualKeyboardAPI

### ISSUE THREAD

**Issue by gked** [w3c/virtual-keyboard#4]
Hi All,

Would you please reply to this thread whether you are looking to use VirtualKeyboardAPI in your development.
When you reply, please indicate your affiliation with a company or an organization.

Links to the explainers.
https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/VirtualKeyboardAPI/explainer.md
https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/VirtualKeyboardPolicy/explainer.md

API usage [examples](https://github.com/BoCupp-Microsoft/VirtualKeyboard).

Thanks!

**Comment by snianu** [comment]
Thank you for all the support! The VK API has been shipped in Chromium and will be available in M94!
