### ISSUE TITLE
Default value of overlaysContent

### ISSUE THREAD

**Issue by lpd-au** [w3c/virtual-keyboard#8]
The spec currently describes `overlaysContent` as _"A boolean, initially `false`."_ It is my understanding that [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=404315)/[Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1007286) and [Safari](https://bugs.webkit.org/show_bug.cgi?id=176205) currently have diverging behaviour on whether the on-screen keyboard overlays the visual viewport, and changing this behaviour would involve a significant web compatibility risk. Unless Safari has expressed an intent to take on this risk and change their default behaviour to match Chrome and Firefox, for backwards compatibility reasons I propose the spec should permit user-agents to define an initial value of  `true`.

**Comment by snianu** [comment]
@lpd-au There is no change in the behavior if `overlaysContent` is not set to true. It will just follow the existing logic for scrolling editable element into view when keyboard shows up, resizing visual or layout viewports etc. If you notice any changes please file a bug in the corresponding Browser's bug repo.

**Comment by lpd-au** [comment]
@snianu isn't that rather confusing design/nomenclature, if setting `overlaysContent` to `false` still allows the virtual keyboard to overlay content on Safari/iOS as per existing logic?

**Comment by snianu** [comment]
So, the goal here is to not resize both layout & visual viewports when `overlaysContent` is set to true. Safari does resize the visual viewport, but the layout viewport is unchanged. See [this ](https://github.com/w3ctag/design-reviews/issues/498#issuecomment-698107446)post for more context & test page that you can use to test this scenario.
